name: azalea
channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.6
- numba=0.36.*
- numpy=1.13.*
- pytorch-cpu=0.4.1
- pyyaml=3.11.*
- scipy=1.0.*
- click=6.*
- mkl
- tensorflow=1.8.*
- tensorboard=1.8.*
- tensorboardX=1.2.*
- smart_open=1.6.*
